### ISSUE TITLE
Sample app scripts are in share folder but specific to the sample app.

### ISSUE THREAD

**Issue by pmalarme** [Azure/aca-landing-zone-accelerator#112]
The script [jumpbox-setup.sh](https://github.com/Azure/aca-landing-zone-accelerator/blob/main/scenarios/shared/scripts/jumpbox-setup.sh) is dedicated to the sample app `Fine Collection Service` and is nor shared nor reusable for other workload. It should be in the `Fine Collection Service` sample app folder.

**Comment by thotheod** [comment]
thanks you are right. Can you do a PR?
