### ISSUE TITLE
Blue / Green deployment option with landing zone

### ISSUE THREAD

**Issue by sowsan** [Azure/aca-landing-zone-accelerator#116]
What is the best way to deploy the container apps with blue green deployment option mentioned here https://learn.microsoft.com/en-us/azure/container-apps/blue-green-deployment?pivots=azure-cli

Can we modify the ACA bicep deployment file ? are there any sample available for the same? 

Thank you!

**Comment by thotheod** [comment]
Hi, the scenario we cover in the LZA is not exposing ACA ingress to the public internet. The applications deployed on ACA will be published to the internet through Application Gateway. Having said that, I think the most appropriate approach for a blue-green deployment type is to do it at the ACA environment level. Possibly something like the [Blue-green deployment of AKS clusters](https://learn.microsoft.com/azure/architecture/guide/aks/blue-green-deployment-for-aks)
