### ISSUE TITLE
README.md is not up to date in the latest main version, leading to confusion?

### ISSUE THREAD

**Issue by RustinAlexandruC** [Azure/aca-landing-zone-accelerator#124]
Hello,

In the latest main version, [c49ea0f](https://github.com/Azure/aca-landing-zone-accelerator/commit/c49ea0f787331032bbb3c764bc921f33f149afb3) file scenarios/aca-internal/terraform/modules/01-hub/main.tf

there is no mention of the jumpbox in the main.tf file, while the README.md file mentions you will deploy a jumpbox (which is optional)

>After executing these steps you'll have the hub resource group (rg-lzaaca-hub-dev-reg, by default) populated with a regional virtual network, Azure Bastion, and jump box virtual machines.

>Resources
>Hub resource group
>Hub virtual network
>Azure Bastion (optional)
>Jump box virtual machine (optional)

Am I missing something here? Apologies for any mistake, beginner here.

**Comment by thotheod** [comment]
You are right, the documentation is kind of outdated there. The current implementation (documentation needs to be fixed) is deploying a [Jumpbox](https://github.com/Azure/aca-landing-zone-accelerator/blob/682b9cb70c6454a73257711f9edef25b1ba20290/scenarios/aca-internal/terraform/modules/02-spoke/main.tf#L104) in the spoke.

**Comment by thotheod** [comment]
fixed documentation
