### ISSUE TITLE
Guide for multi region ACAs

### ISSUE THREAD

**Issue by falsadoo** [Azure/aca-landing-zone-accelerator#131]
I am new to this can someone help me setup two Aca environments in two regions using this architecture?

**Comment by kpantos** [comment]
Hi @falsadoo, thanks for reaching out. 
You can follow the design principles and guidance under [Azure Well-Architected Framework](https://learn.microsoft.com/en-us/azure/well-architected/) also check out the reference implementation at [Enterprise App Patterns: Reliable Web App Pattern - .NET](https://learn.microsoft.com/en-us/shows/enterprise-app-patterns-reliable-web-app-pattern-dotnet/) although the hosting service is web apps the principles are the same and you can change the hosting service with azure container apps.
