### ISSUE TITLE
Can this reference architecture include BC & DR?

### ISSUE THREAD

**Issue by garrettlondon1** [Azure/aca-landing-zone-accelerator#153]

**Comment by kpantos** [comment]
Thanks for sharing this feedback @garrettlondon1. 
Given that you can always deploy a new stamp of the infrastructure at another region using the provided templates in a DR scenario, can you please share which BC & DR features you'd like to see enabled? Are you interested in adding data/state disaster recovery?

**Comment by garrettlondon1** [comment]
Are there better ways to do DR for mission critical workflows than to deploy a new stack to another region?

This would require the switching of connection strings in the app, a redeployment, etc, correct?

Thank you for your response!

**Comment by kpantos** [comment]
There are indeed but the decisions and implementation should be the result of customer conversations as there are a lot of diverse ways to tackle resiliency and associated costs with them, which depend on the application needs. For example, a customer might be ok with spinning up a new stamp and changing DNS and connection strings at the env variables while another might require an active-stdby or even an active-active setup based on the application RTO and RPO requirements.

The Landing Zone accelerator's purpose is to build a secure baseline for customers' applications on which they can build on to add all the needed features. For more guidance on building a mission critical hosting environment for running containerized applications you can refer to our [Mission Critical](https://github.com/Azure/Mission-Critical) guidance.
