### ISSUE TITLE
IP restriction recommendations for publicly accessible container apps

### ISSUE THREAD

**Issue by Nicwalle** [Azure/aca-landing-zone-accelerator#57]
Hi, 
The landing zone accelerator does not mention the IP restriction functionality: https://learn.microsoft.com/en-us/azure/container-apps/ip-restrictions?pivots=azure-portal 

In some scenarios, it makes sense to have a public facing container app rather than putting it behind an application gateway. It would thus be nice to have some discussions and recommendations regarding such a scenario.
Thank you.

**Comment by thotheod** [comment]
Hi @Nicwalle , thank you for your recommendation. I assume a valid scenario to use IP Restrictions would be to use a third party CDN/WAF service, so we updated the [Networking Design Area](https://github.com/Azure/aca-landing-zone-accelerator/blob/main/docs/design-areas/networking.md) accordingly. Do you have something else in mind?
