### ISSUE TITLE
GitHub Action doesn't create ACA secure baseline

### ISSUE THREAD

**Issue by reza8iucs** [Azure/aca-landing-zone-accelerator#64]
I forked the repo. When I run the GitHub action it creates a bunch of LBs , possibly leftover from another deployment library,  instead of an ACA app deployed in VNET internal mode . What am I doing wrong?

There is an ACA environment but there is no app, and there is no sign of AppGW and AFD. Hub and spoke artefacts are ok.

![image](https://github.com/Azure/aca-landing-zone-accelerator/assets/110741554/0aed88de-ffc5-401d-afd6-b90d5e19c902)

To add more context, even though i see all steps in the deployments have completed successfully , I see this error message in the deployment log in GitHub action:

```
Error: WARNING: /home/runner/work/WiseACAOps/WiseACAOps/scenarios/shared/bicep/private-networking.bicep(49,11) : Warning BCP334: The provided value has no configured minimum length and may be too short to assign to a target with a configured minimum length of 2.
/home/runner/work/WiseACAOps/WiseACAOps/scenarios/shared/bicep/private-networking.bicep(49,11) : Warning BCP335: The provided value has no configured maximum length and may be too long to assign to a target with a configured maximum length of 64
```

**Comment by reza8iucs** [comment]
Update: tried to do the step by step guide and it looks like the name of the deployments are inconsistent and that doesn't work either. Finally tried to do the first deployment option (cut to the end option) and it worked.  I still have no clue what's the above resource group and those load balancers are created for!

**Comment by thotheod** [comment]
Hi @reza8iucs. If I understood correctly you managed to deploy the ACA LZA after all, right? 
GitHub action deploys, what is being described here: https://github.com/Azure/aca-landing-zone-accelerator/tree/main/scenarios/aca-internal/bicep#deployment-experiences, meaning no sample app, appgateway or front door. 
You can aither change the parameter `deployHelloWorldSample` to true, to let the deployment deploy a simple hello world application, exposed through an application gateway. Alternatively, you can leave  `deployHelloWorldSample` to `false` and follow the steps to deploy the java fine collection sample application, as described here: 

https://github.com/Azure/aca-landing-zone-accelerator/blob/main/scenarios/aca-internal/bicep/sample-apps/java-fine-collection-service/docs/02-container-apps.md

Regarding the resource group you ask about: 
ACA is using AKS under the hood. so the MC_* resource group you see is the AKS's Managed Cluster resources, more see here: https://learn.microsoft.com/en-us/azure/aks/faq#why-are-two-resource-groups-created-with-aks
