### ISSUE TITLE
Error when running terraform plan of aca-internal - ClientIP is required (supporting services)

### ISSUE THREAD

**Issue by reidav** [Azure/aca-landing-zone-accelerator#81]
Following the steps highlighted by the README.md in the root folder using terraform :
- Create storage account
- Review terraform.tfvars
- Try to execute terraform plan

It says clientIP is not provided in sub modules, i'm assuming i should be able to provision it using default value.

```
codespace ➜ .../aca-landing-zone-accelerator/scenarios/aca-internal/terraform (main) $ terraform plan --var-file terraform.tfvars -out tfplan
╷
│ Error: Missing required argument
│ 
│   on main.tf line 35, in module "supportingServices":
│   35: module "supportingServices" {
│ 
│ The argument "clientIP" is required, but no definition was found.
```

**Comment by ibersanoMS** [comment]
I've updated the Terraform implementation to support optional input of the client IP address, added a line to the TF vars file to show where to define it and added it to the readme instructions (See branch attached to this issue). The Client IP is the IP address of the machine handling the Terraform deployment and is used to provide access to the KeyVault to create the Application Gateway. If you'd like to do the deployment all in one go, you can add your IP address and it will deploy Application Gateway. If you would like to keep the KeyVault private, I've added a note to comment out the Application Gateway module, leave the clientIP variable undefined, and to deploy the App Gateway from the jumpbox on the network.
